In [1]:
import numpy as np
import torch

In [16]:
ukb_weights = torch.load("/neurospin/dico/agaudin/Runs/09_new_repo/Output/supervised/pretrained_UKB/UKB_pretrained_weights.ckpt", map_location=torch.device('cpu'))
post_training_weights = torch.load("/neurospin/dico/agaudin/Runs/09_new_repo/Output/2023-09-07/15-16-47_54/logs/best_model_weights.pt", map_location=torch.device('cpu'))
end_weights = torch.load("/neurospin/dico/agaudin/Runs/09_new_repo/Output/2023-09-07/15-33-26_155/logs/lightning_logs/version_0/checkpoints/epoch=24-step=400.ckpt", map_location=torch.device('cpu'))

In [17]:
ukb_weights['state_dict'].keys()

dict_keys(['backbones.0.encoder.conv0.weight', 'backbones.0.encoder.conv0.bias', 'backbones.0.encoder.norm0.weight', 'backbones.0.encoder.norm0.bias', 'backbones.0.encoder.norm0.running_mean', 'backbones.0.encoder.norm0.running_var', 'backbones.0.encoder.norm0.num_batches_tracked', 'backbones.0.encoder.conv0a.weight', 'backbones.0.encoder.conv0a.bias', 'backbones.0.encoder.norm0a.weight', 'backbones.0.encoder.norm0a.bias', 'backbones.0.encoder.norm0a.running_mean', 'backbones.0.encoder.norm0a.running_var', 'backbones.0.encoder.norm0a.num_batches_tracked', 'backbones.0.encoder.conv1.weight', 'backbones.0.encoder.conv1.bias', 'backbones.0.encoder.norm1.weight', 'backbones.0.encoder.norm1.bias', 'backbones.0.encoder.norm1.running_mean', 'backbones.0.encoder.norm1.running_var', 'backbones.0.encoder.norm1.num_batches_tracked', 'backbones.0.encoder.conv1a.weight', 'backbones.0.encoder.conv1a.bias', 'backbones.0.encoder.norm1a.weight', 'backbones.0.encoder.norm1a.bias', 'backbones.0.encoder.n

In [18]:
print(ukb_weights['state_dict']['backbones.0.encoder.conv0.weight'].shape)
print(post_training_weights['state_dict']['backbones.0.encoder.conv0.weight'].shape)
print(end_weights['state_dict']['backbones.0.encoder.conv0.weight'].shape)

i = np.random.randint(16)
print(i)

print(ukb_weights['state_dict']['backbones.0.encoder.conv0.weight'][i])
print(post_training_weights['state_dict']['backbones.0.encoder.conv0.weight'][i])
print(end_weights['state_dict']['backbones.0.encoder.conv0.weight'][i])

torch.Size([16, 1, 3, 3, 3])
torch.Size([16, 1, 3, 3, 3])
torch.Size([16, 1, 3, 3, 3])
4
tensor([[[[-0.1364,  0.0224,  0.0147],
          [-0.7712,  0.2243, -0.0767],
          [ 0.0133,  0.1830,  0.0624]],

         [[-0.0436,  0.0022,  0.0083],
          [-0.1404,  0.2402,  0.1313],
          [ 0.2304, -0.8532,  0.0089]],

         [[-0.0023, -0.0192, -0.1292],
          [ 0.1419,  0.2133, -0.6668],
          [-0.2010,  0.2161, -0.0185]]]])
tensor([[[[-0.1364,  0.0224,  0.0147],
          [-0.7712,  0.2243, -0.0767],
          [ 0.0133,  0.1830,  0.0624]],

         [[-0.0436,  0.0022,  0.0083],
          [-0.1404,  0.2402,  0.1313],
          [ 0.2304, -0.8532,  0.0089]],

         [[-0.0023, -0.0192, -0.1292],
          [ 0.1419,  0.2133, -0.6668],
          [-0.2010,  0.2161, -0.0185]]]])
tensor([[[[-0.1364,  0.0224,  0.0147],
          [-0.7712,  0.2243, -0.0767],
          [ 0.0133,  0.1830,  0.0624]],

         [[-0.0436,  0.0022,  0.0083],
          [-0.1404,  0.2402,  0.1313]